const product = {
  Products: [
    {
      id: 1,
      name: "Ras Malai pcs",
      image: "rasmalai.jpg",
      price: 38,
      offer: 20,
      quantity: 1,
    },
    {
      id: 2,
      name: "Dry Petha",
      image: "dryPetha.jpg",
      price: 80,
      offer: 0,
      quantity: 1,
    },
    {
      id: 3,
      name: "Rajasthani Jalebi",
      image: "jalebi.jpg",
      price: 110,
      offer: 20,
      quantity: 1,
    },
    {
      id: 4,
      name: "Rajasthani Laddoo",
      image: "rajasthaniLadoo.jpg",
      price: 105,
      offer: 0,
      quantity: 1,
    },
    {
      id: 5,
      name: "Pista Burfi",
      image: "pistaBurfi.jpg",
      price: 300,
      offer: 20,
      quantity: 1,
    },
    {
      id: 6,
      name: "Bengali Rasgulla pcs",
      image: "bestSeller2.webp",
      price: 24,
      offer: 20,
      quantity: 1,
    },
    {
      id: 7,
      name: "Atta Laddoo",
      image: "aataLadoo.jpg",
      price: 105,
      offer: 20,
      quantity: 1,
    },
    {
      id: 8,
      name: "Bengali Balushai",
      image: "balushahi.jpeg",
      price: 225,
      offer: 20,
      quantity: 1,
    },
    {
      id: 9,
      name: "SugarFree KesarPeda",
      image: "kesarPeda.jpg",
      price: 300,
      offer: 0,
      quantity: 1,
    },
    {
      id: 10,
      name: "SugarFree KalaJam",
      image: "bestSeller1.webp",
      price: 100,
      offer: 20,
      quantity: 1,
    },
    {
      id: 11,
      name: "Burfi Plain",
      image: "burfi.jpg",
      price: 140,
      offer: 20,
      quantity: 1,
    },
    {
      id: 12,
      name: "Burfi Chocolate",
      image: "burfiChocolate.jpg",
      price: 120,
      offer: 0,
      quantity: 1,
    },
  ],
};
export default product;
